directories:
  output: build
  buildResources: build
productName: 晞格玛·云
copyright: Copyright © 私塾国际学府
appId: com.sishu.hulkbuster
generateUpdatesFilesForAllChannels: true
releaseInfo:
  releaseNotes: 1. 修复退出群聊报错 <br> 2. 切换对话清空消息 <br> 3. 群聊查看群成员可发送消息
asar: true
compression: maximum
publish:
  - provider: generic
    url: 'http://192.168.2.115:82/download/'
    channel: latest
files:
  - filter:
      - dist/electron/**/*
extraResources:
  - filter:
      - static
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: icon/sishu.png
linux:
  icon: build/icons
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 8.2.5
